baseURL = 'https://dannyvilchez.github.io/'
languageCode = 'en-us'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Blog about Data Engineer and Existentialism"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hey.'
homeIntroContent = """
I'm a self-taught data engineer obcessed with building projects and overthinking the human condition
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2006-01-02'

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = false
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/vilchezdanny/"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/dannyvilchez"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

[caches]
[caches.images]
dir = ':cacheDir/images'
